### ISSUE TITLE
Require Install Tool Password before writing to LocalConfiguration.php

### ISSUE THREAD

**Issue by chris246** [IchHabRecht/TYPO3-hosts_pattern#11]
Just as a suggestion:

Usually, editing trustedHostsPattern requires either file access or providing the install tool password,  
Using this extension, this protection can be bypassed.

---
Thank you very much for this great tool!

**Comment by IchHabRecht** [comment]
Hi @chris246,

Sorry for the late answer. As the backend module is accessible only for admins, I think this is not an issue that needs to be tackled by the extension. An administrator can install any extension that might change the configuration or even more. But for the update I'll bound the module to system maintainers only. Thank you for that hint.
