### ISSUE TITLE
Outdated extension ?

### ISSUE THREAD

**Issue by Patta** [IchHabRecht/TYPO3-hosts_pattern#2]
is this extension maintained anymore?

TYPO3 repo says:

> Outdated extension
> This extension supports none of the currently supported TYPO3 core versions or was uploaded before the release of the oldest TYPO3 core version.
> It may no longer be maintained or supported by the extension owner.
> Please be careful using this extension for your up-to-date TYPO3 instance.

https://typo3.org/extensions/repository/view/hosts_pattern

**Comment by IchHabRecht** [comment]
Hi Pat,

Thanks for your report. This problem was solved within the TER.
