### ISSUE TITLE
[FEATURE] add redirect option if host is not trusted

### ISSUE THREAD

**Issue by Patta** [IchHabRecht/TYPO3-hosts_pattern#7]
If a host is not trusted a error message is shown. It would be nice if a domain can be configured, which is forwarded from the error message.

**Comment by IchHabRecht** [comment]
As the trusted hosts pattern concept was introduces as another security layer, this extension will not any functionality to by-pass the protection. You may find further information in the provided security bulletin [TYPO3-CORE-SA-2014-001](https://typo3.org/teams/security/security-bulletins/typo3-core/typo3-core-sa-2014-001/)
